"""ilk yenileme

Revision ID: 0c402c04638b
Revises: 
Create Date: 2021-04-09 21:15:34.695556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c402c04638b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.String(length=70), nullable=True),
    sa.Column('tarix', sa.String(length=70), nullable=True),
    sa.Column('derman_id', sa.String(length=70), nullable=True),
    sa.Column('miqdar', sa.String(length=70), nullable=True),
    sa.Column('alish_qiymeti', sa.String(length=70), nullable=True),
    sa.Column('satish_qiymeti', sa.String(length=70), nullable=True),
    sa.Column('qeyd_yeri', sa.String(length=250), nullable=True),
    sa.Column('endirim', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alish')
    # ### end Alembic commands ###
