"""birin coxa elaqe

Revision ID: 40d6aa92db3f
Revises: 0c402c04638b
Create Date: 2021-04-11 12:31:38.764689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d6aa92db3f'
down_revision = '0c402c04638b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alish', sa.Column('barkod', sa.String(length=30), nullable=True))
    op.add_column('alish', sa.Column('mebleg', sa.String(length=70), nullable=True))
    op.add_column('alish', sa.Column('vahid', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'alish', 'firma', ['firma_id'], ['id'])
    op.create_foreign_key(None, 'alish', 'derman', ['derman_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alish', type_='foreignkey')
    op.drop_constraint(None, 'alish', type_='foreignkey')
    op.drop_column('alish', 'vahid')
    op.drop_column('alish', 'mebleg')
    op.drop_column('alish', 'barkod')
    # ### end Alembic commands ###
